In [163]:
import pandas as pd

url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/french-ambs.csv"

df = pd.read_csv(url)
df.head(10)

   id                      name    place  year    lat   long      lat_long
0   0        Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1        Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2        Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3        Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4        Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57
5   5        Bapaume, Robert de  England  1516  51.51  -0.12  51.51, -0.12
6   6  Passano, Jean-Joachim de  England  1527  51.51  -0.12  51.51, -0.12
7   7               De Monpreat  England  1532  51.51  -0.12  51.51, -0.12
8   8           Du Bellay, Jean  England  1530  51.51  -0.12  51.51, -0.12
9   9     Castelnau, Antoine de  England  1534  51.51  -0.12  51.51, -0.12

In [164]:
# file paths
# absolute file path
# /Users/corvosp/Documents/python-class/
# relative path (cool)
# ./ [where we are]
# ../ [go up one folder]
# ../../../ [go up 3 folders]
# ./data/

In [165]:
# df.to_csv("./data/french-ambs.csv", index = False)

In [166]:
df = pd.read_csv("./data/french-ambs.csv")
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [167]:
df.loc[0, "name"]

'Richer, Christophe'

In [168]:
df.loc[df["place"] == "England", "name"]

5            Bapaume, Robert de
6      Passano, Jean-Joachim de
7                   De Monpreat
8               Du Bellay, Jean
9         Castelnau, Antoine de
                 ...
817     La Pommeraie, Gilles de
818                   Pot, Jean
819              De Selve, Odet
820             La Fin, Jean de
821    L'Aubspine, Guillaume de
Name: name, Length: 93, dtype: object

In [169]:
# finds location by index
df.iloc[0, 1]

'Richer, Christophe'

In [170]:
df.iloc[72]

id                                           72
name        Rougier, François, Baron of Ferrals
place                               Netherlands
year                                       1568
lat                                       52.37
long                                       4.89
lat_long                            52.37, 4.89
Name: 72, dtype: object

In [171]:
for i in range(10):
    print(df.iloc[i])

id                           0
name        Richer, Christophe
place                  Denmark
year                      1543
lat                      55.68
long                     12.57
lat_long          55.68, 12.57
Name: 0, dtype: object
id                           1
name        Richer, Christophe
place                  Denmark
year                      1541
lat                      55.68
long                     12.57
lat_long          55.68, 12.57
Name: 1, dtype: object
id                           2
name        Danzay, Charles de
place                  Denmark
year                      1561
lat                      55.68
long                     12.57
lat_long          55.68, 12.57
Name: 2, dtype: object
id                           3
name        Danzay, Charles de
place                  Denmark
year                      1563
lat                      55.68
long                     12.57
lat_long          55.68, 12.57
Name: 3, dtype: object
id                           4
name        Danzay, Charles de
place                  Denmark
year                      1582
lat                      55.68
long                     12.57
lat_long          55.68, 12.57
Name: 4, dtype: object
id                           5
name        Bapaume, Robert de
place                  England
year                      1516
lat                      51.51
long                     -0.12
lat_long          51.51, -0.12
Name: 5, dtype: object
id                                 6
name        Passano, Jean-Joachim de
place                        England
year                            1527
lat                            51.51
long                           -0.12
lat_long                51.51, -0.12
Name: 6, dtype: object
id                     7
name         De Monpreat
place            England
year                1532
lat                51.51
long               -0.12
lat_long    51.51, -0.12
Name: 7, dtype: object
id                        8
name        Du Bellay, Jean
place               England
year                   1530
lat                   51.51
long                  -0.12
lat_long       51.51, -0.12
Name: 8, dtype: object
id                              9
name        Castelnau, Antoine de
place                     England
year                         1534
lat                         51.51
long                        -0.12
lat_long             51.51, -0.12
Name: 9, dtype: object

In [172]:
# df.iloc[0.0] = 0

In [173]:
df.iloc[100:105]

,id,name,place,year,lat,long,lat_long
100,100,"Bellièvre, Pomponne de",Swiss Cantons,1570,46.94,7.45,"46.94, 7.45"
101,101,"Bellièvre, Jean de, sr. de Hautefort",Swiss Cantons,1579,46.94,7.45,"46.94, 7.45"
102,102,"Vigier, Jean",Swiss Cantons,1581,46.94,7.45,"46.94, 7.45"
103,103,"De Pins, Jean",Venice,1517,45.44,12.33,"45.44, 12.33"
104,104,"De Pins, Jean",Venice,1518,45.44,12.33,"45.44, 12.33"

In [174]:
# .at[], .iat[]
# the same as .loc and .iloc but only used for individual cells

df.at[0, "place"]

'Denmark'

In [175]:
df.iat[0,3]

np.int64(1543)

In [176]:
# df.iat[0,3] = 1546

In [177]:
# iterating
df.columns

Index(['id', 'name', 'place', 'year', 'lat', 'long', 'lat_long'], dtype='object')

In [178]:
for col in df.columns:
    print(col, pd.api.types.is_numeric_dtype(df[col]))

id True
name False
place False
year True
lat True
long True
lat_long False

In [179]:
# loop pver rows
#iterrows returns a list 
# let's rename Denmark => Den.
for idx, item in df.iterrows():
    print(item["place"])

Denmark
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Portugal
Rome
Portugal
Rome
Rome
Rome
Rome
Savoy
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Venice
Denmark
England
England
England
England
England
England
England
Grisons
England
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
Denmark
England
England
Denmark
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Savoy
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Ferrara
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Rome
Rome
Scotland
Scotland
Spain
Venice
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
Ferrara
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Spain
Spain
Scotland
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Poland
Poland
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Ferrara
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Rome
Rome
Rome
Rome
Rome
Savoy
Saxony
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Tuscany
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Venice
Denmark
Denmark
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Savoy
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Swiss Cantons
Venice
Venice
Holy Roman Empire

In [180]:
# itertuples() is faster than iterrows

for item in df.itertuples():
    print(item.place) # named tuples use dot noteation

Denmark
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Portugal
Rome
Portugal
Rome
Rome
Rome
Rome
Savoy
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Venice
Denmark
England
England
England
England
England
England
England
Grisons
England
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
Denmark
England
England
Denmark
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Savoy
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Ferrara
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Rome
Rome
Scotland
Scotland
Spain
Venice
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
Ferrara
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Spain
Spain
Scotland
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Poland
Poland
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Ferrara
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Rome
Rome
Rome
Rome
Rome
Savoy
Saxony
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Tuscany
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Venice
Denmark
Denmark
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Savoy
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Swiss Cantons
Venice
Venice
Holy Roman Empire

In [181]:
# dont do this for Denmark => Den.
for item in df.itertuples():
    if item.place == "Denmark":
        df.at[item.Index, "place"] = "Den."
df["place"].unique() # get unique values existing in column

array(['Den.', 'England', 'Geneva', 'Grisons', 'Holy Roman Empire',
       'Netherlands', 'Ottoman Empire', 'Portugal', 'Rome', 'Scotland',
       'Spain', 'Swiss Cantons', 'Venice', 'Poland', 'Savoy', 'Ferrara',
       'Saxony', 'Tuscany'], dtype=object)

In [182]:
# England => Eng.
# if only changing one name, use .loc[]
df.loc[df["place"] == "England", "place"] = "Eng."
df["place"].unique()

array(['Den.', 'Eng.', 'Geneva', 'Grisons', 'Holy Roman Empire',
       'Netherlands', 'Ottoman Empire', 'Portugal', 'Rome', 'Scotland',
       'Spain', 'Swiss Cantons', 'Venice', 'Poland', 'Savoy', 'Ferrara',
       'Saxony', 'Tuscany'], dtype=object)

In [183]:
# .replace() for multiple

# runs an index through a dictionary and replaces the key.
# hash = {
#    "Holy Roman Emprie": "HRE",
#    "Geneva": "Gen."
# }
hash = {name:name[:3] for name in df["place"].unique() if len(name) != 4}
hash

{'Geneva': 'Gen',
 'Grisons': 'Gri',
 'Holy Roman Empire': 'Hol',
 'Netherlands': 'Net',
 'Ottoman Empire': 'Ott',
 'Portugal': 'Por',
 'Scotland': 'Sco',
 'Spain': 'Spa',
 'Swiss Cantons': 'Swi',
 'Venice': 'Ven',
 'Poland': 'Pol',
 'Savoy': 'Sav',
 'Ferrara': 'Fer',
 'Saxony': 'Sax',
 'Tuscany': 'Tus'}

In [184]:
hash = {name:f"{name[:3]}." for name in df["place"].unique() if len(name) != 4}
hash
df['place'] = df['place'].replace(hash)

In [185]:
# Pandas operators & (and), | (or), ~ (not)
df.loc[(df["place"] == "Den.") & (df['year'] < 1561) & (df['year'] > 1550)].count()

id          4
name        4
place       4
year        4
lat         4
long        4
lat_long    4
dtype: int64

In [186]:
# use ~
df.loc[~(df["place"] == "Den.") & (df['year'] < 1561) & (df['year'] > 1550)].count()

id          117
name        117
place       117
year        117
lat         117
long        117
lat_long    117
dtype: int64

In [187]:
imp_ambs = ["Eng.", "Ott.", "Ven."]

df.loc[(df["place"].isin(imp_ambs)) & (df['year'] < 1561) & (df['year'] > 1550)].count()

id          40
name        40
place       40
year        40
lat         40
long        40
lat_long    40
dtype: int64

In [189]:
for item in df['place'].unique():
    if item in imp_ambs:
        print(f"is {item} in ambs list? {item in imp_ambs}")

is Eng. in ambs list? True
is Ott. in ambs list? True
is Ven. in ambs list? True