- What is a dataframe (pandas)
- create df
- vectorized operations
- access rows, coluns, cells. (.loc, .iloc, .at)
- change values
- sort values

In [1]:
import pandas as pd

In [2]:
from typing import List
data_list: List[int] = [1,2,3,4,5]

s1 = pd.Series(data_list)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
s1 = pd.Series(data = data_list, index = ["a","b","c","d","e"])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
s1 = s1 + 23
s1

a    24
b    25
c    26
d    27
e    28
dtype: int64

In [5]:
type(s1)

pandas.core.series.Series

In [6]:
# DF = a collection of Series objects - columns must be homogenous (same data type),
# every column has to have the same number of data entries

# Dictionary creation
data = {
    "name" : ["Nate", "Rebecca", "Edwin", "Preston"],
    "age" : [39, 40, 11, 7],
    "year" : ["Senior", "Junior", "Sophomore", "Freshmen"],
}
students_df = pd.DataFrame(data=data)
students_df = students_df.set_index("name")
students_df

         age       year
name
Nate      39     Senior
Rebecca   40     Junior
Edwin     11  Sophomore
Preston    7   Freshmen

In [7]:
students_df = students_df.reset_index()
students_df

      name  age       year
0     Nate   39     Senior
1  Rebecca   40     Junior
2    Edwin   11  Sophomore
3  Preston    7   Freshmen

In [8]:
# Row-based creation
import random

names = ["Messi", "Ronaldo", "Neymar", "Pulisc", "Mbappe"]
goals_per_game = [random.random() for _ in names]
games = [round(random.random() * 1000) for _ in names]

cols = ["name", "goals/game", "games"]
stats = [[names[i], goals_per_game[i], games[i]] for i in range(5)]

stats_df = pd.DataFrame(data=stats, columns=cols)
stats_df

      name  goals/game  games
0    Messi    0.914255    929
1  Ronaldo    0.519991    723
2   Neymar    0.703123    359
3   Pulisc    0.825497    304
4   Mbappe    0.377025    444

In [9]:
stats_df["new_col"] = 0
stats_df

      name  goals/game  games  new_col
0    Messi    0.914255    929        0
1  Ronaldo    0.519991    723        0
2   Neymar    0.703123    359        0
3   Pulisc    0.825497    304        0
4   Mbappe    0.377025    444        0

In [10]:
stats_df = stats_df.drop(columns = ["new_col"])
stats_df

      name  goals/game  games
0    Messi    0.914255    929
1  Ronaldo    0.519991    723
2   Neymar    0.703123    359
3   Pulisc    0.825497    304
4   Mbappe    0.377025    444

In [11]:
stats_df['goals'] = stats_df["goals/game"] * stats_df["games"]
stats_df

      name  goals/game  games       goals
0    Messi    0.914255    929  849.342547
1  Ronaldo    0.519991    723  375.953768
2   Neymar    0.703123    359  252.421210
3   Pulisc    0.825497    304  250.950983
4   Mbappe    0.377025    444  167.399003

In [12]:
stats_df = stats_df.rename(columns = {"goals/game": "goals_p_game"})
# stats_df.rename(columns = {"goals/game": "goals_p_game"}, inplace = True)
stats_df

      name  goals_p_game  games       goals
0    Messi      0.914255    929  849.342547
1  Ronaldo      0.519991    723  375.953768
2   Neymar      0.703123    359  252.421210
3   Pulisc      0.825497    304  250.950983
4   Mbappe      0.377025    444  167.399003

In [13]:
stats_df["name"]

0      Messi
1    Ronaldo
2     Neymar
3     Pulisc
4     Mbappe
Name: name, dtype: object

In [14]:
stats_df["name"] = stats_df["name"].str.lower()
stats_df

      name  goals_p_game  games       goals
0    messi      0.914255    929  849.342547
1  ronaldo      0.519991    723  375.953768
2   neymar      0.703123    359  252.421210
3   pulisc      0.825497    304  250.950983
4   mbappe      0.377025    444  167.399003

In [15]:
stats_df[["name", "games"]]

      name  games
0    messi    929
1  ronaldo    723
2   neymar    359
3   pulisc    304
4   mbappe    444

In [16]:
# filtering with .loc

stats_df.loc[0,"name"]

'messi'

In [17]:
stats_df.loc[0]

name                 messi
goals_p_game      0.914255
games                  929
goals           849.342547
Name: 0, dtype: object

In [18]:
stats_df.loc[:, "name"]

0      messi
1    ronaldo
2     neymar
3     pulisc
4     mbappe
Name: name, dtype: object

In [19]:
stats_df.loc[1:2, "name"] # in df, second item after colon is inclusive

1    ronaldo
2     neymar
Name: name, dtype: object

In [20]:
l = [1,2,3,4,5]
l[1:2] # in a list the second item is exclusive

[2]

In [21]:
stats_df.loc[:,"name":"goals"]

      name  goals_p_game  games       goals
0    messi      0.914255    929  849.342547
1  ronaldo      0.519991    723  375.953768
2   neymar      0.703123    359  252.421210
3   pulisc      0.825497    304  250.950983
4   mbappe      0.377025    444  167.399003

In [22]:
# boolean logic with .loc

stats_df.loc[stats_df["goals_p_game"] > 0.5]

      name  goals_p_game  games       goals
0    messi      0.914255    929  849.342547
1  ronaldo      0.519991    723  375.953768
2   neymar      0.703123    359  252.421210
3   pulisc      0.825497    304  250.950983

In [23]:
stats_df.loc[stats_df["goals_p_game"] > 0.5, "name"]

0      messi
1    ronaldo
2     neymar
3     pulisc
Name: name, dtype: object

In [24]:
stats_df.loc[stats_df["name"] == "mbappe", "name"] = "ronaldo"
stats_df.loc[stats_df["goals_p_game"] > 0.5, "name"] = "mbappe"
stats_df

      name  goals_p_game  games       goals
0   mbappe      0.914255    929  849.342547
1   mbappe      0.519991    723  375.953768
2   mbappe      0.703123    359  252.421210
3   mbappe      0.825497    304  250.950983
4  ronaldo      0.377025    444  167.399003

In [25]:
# .iloc , .at , .iat